---
- hosts: tor
  vars:
    sudo: yes
    tor_SocksPort: 127.0.0.1:9001
    tor_SocksPolicy:
      - accept 127.0.0.0/8
      - reject *
    tor_Log:
      - debug file /var/log/tor/log
      - notice syslog
    tor_DataDirectory: /var/lib/tor
    tor_ControlPort: 127.0.0.1:1212
    tor_HashedControlPassword: '16:872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4A'
    tor_CookieAuthentication: 1
    tor_HiddenService:
      - Dir: /tmp
        Port: 
          - tor_port: 999
            local_address: 127.0.0.1
            local_port: 888
          - tor_port: 998
            local_address: 127.0.0.2
            local_port: 997
      - Dir: /run
        Port:
          - tor_port: 1244
            local_address: 127.0.0.3
            local_port: 21
    tor_ORPort: 127.0.0.1:5555
    tor_Address: test.example
    tor_Nickname: ansibleTor
    tor_RelayBandwidthRate: '100 KB'
    tor_RelayBandwidthBurst: '320 KB'
    tor_AccountingMax: '100 GB'
    tor_AccountingStart: 'month 1 02:00'
    tor_ContactInfo: noreply@test.example
    tor_DirPort:
      - Port: 22222
        DirPortFrontPage: /etc/tor/tor-exit-notice.html
    tor_MyFamily:
      - '0xFFFFFFFF'
      - '0xEEEEEEEE'
    tor_ExitPolicy:
      - accept *:2223
      - reject *:*
    tor_BridgeRelay: 1
    tor_PublishServerDescriptor: 0

  roles:
    - tor
